import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "NextJs - First application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-md m-auto">
        {children}
      </body>
    </html>
  );
}
